---
- hosts: web
  # become: yes

  tasks:
    - name: Create directory
      file:
        path: /root/Devops_Final/DevOps-Final_Exam
        state: directory
        mode: '0755'
    - name: Copy project to server
      synchronize:
        src: ./
        dest: /root/Devops_Final/DevOps-Final_Exam/

    - name: Build docker containers
      shell: |
        cd /root/Devops_Final/DevOps-Final_Exam
        docker compose down
        docker compose up -d --build