---
- hosts: web
  become: yes

  tasks:

    - name: Copy project to server
      synchronize:
        src: "{{ lookup('env','WORKSPACE') }}/"
        dest: /root/Devops_Final/DevOps-Final_Exam/

    - name: Build docker containers
      shell: |
        cd /root/Devops_Final/DevOps-Final_Exam
        docker compose down
        docker compose up -d --build